version: '3.9'

services:
  api:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
